<?php

namespace console\controllers;

use common\lib\helpers\Crontab;
use common\service\TempService;

class TempController extends \yii\console\Controller
{
    public function beforeAction($action)
    {
        if (Crontab::isRunning()) {
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 抓取温度数据
     */
    public function actionCapture() {
        do {
            TempService::capture();
            sleep(5);
        } while (true);
    }

    /**
     * 清理过期数据
     */
    public function actionGc() {
        do {
            TempService::gc();
            sleep(5);
        } while (true);
    }
}
