<?php

namespace frontend\controllers;

use common\lib\helpers\HttpResponse;
use common\service\AdminService;
use common\service\EditService;

class EditController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (!AdminService::isLogin()) {
            \Yii::$app->response->redirect('/admin/');
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $articleId = \Yii::$app->request->get('id');

        $viewdata = EditService::editData($articleId);

        return $this->renderPartial('index', $viewdata);
    }

    public function actionSaveArticle()
    {
        $articleId = \Yii::$app->request->post('article_id');
        $articleTitle = \Yii::$app->request->post('article_title');
        $articleContent = \Yii::$app->request->post('article_content');

        $fields = ['title' => $articleTitle, 'content' => $articleContent];

        $articleId = EditService::saveArticle($articleId, $fields);
        if (empty($articleId)) {
            return HttpResponse::packReturn(1, '保存失败');
        }
        return HttpResponse::packReturn(0, 'success', ['id' => $articleId]);
    }

    public function actionPubArticle() {
        $articleId = \Yii::$app->request->post('article_id');
        $articleTitle = \Yii::$app->request->post('article_title');
        $articleContent = \Yii::$app->request->post('article_content');

        $fields = ['title' => $articleTitle, 'content' => $articleContent, 'status' => 2,];

        $articleId = EditService::saveArticle($articleId, $fields);
        if (empty($articleId)) {
            return HttpResponse::packReturn(1, '发布失败');
        }
        return HttpResponse::packReturn(0, 'success', ['id' => $articleId]);
    }

    public function actionUnpubArticle() {
        $articleId = \Yii::$app->request->post('article_id');
        EditService::unpubArticle($articleId);
        return HttpResponse::packReturn(0);
    }
}
