<?php

namespace frontend\controllers;

use common\lib\helpers\HttpResponse;
use common\service\AdminService;
use common\service\ListService;

class ListController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (!AdminService::isLogin()) {
            \Yii::$app->response->redirect('/admin/');
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $page = \Yii::$app->request->get('page');

        $viewdata = ListService::listArticles($page);
        return $this->renderPartial('index', $viewdata);
    }

    public function actionDeleteArticle() {
        $articleId = \Yii::$app->request->post('article_id');
        ListService::deleteArticle($articleId);
        return HttpResponse::packReturn(0, 'success');
    }
}
